spring.application.name=erp

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:mydb}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

#Hibernate settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

#Swagger settings
springdoc.swagger-ui.path=/docs
